// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeroToHero.CodeFirst.DAL;

#nullable disable

namespace ZeroToHero.CodeFirst.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220815101424_addTablePerType")]
    partial class addTablePerType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZeroToHero.CodeFirst.DAL.BasePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("ZeroToHero.CodeFirst.DAL.Employee", b =>
                {
                    b.HasBaseType("ZeroToHero.CodeFirst.DAL.BasePerson");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("ZeroToHero.CodeFirst.DAL.Manager", b =>
                {
                    b.HasBaseType("ZeroToHero.CodeFirst.DAL.BasePerson");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("ZeroToHero.CodeFirst.DAL.Employee", b =>
                {
                    b.HasOne("ZeroToHero.CodeFirst.DAL.BasePerson", null)
                        .WithOne()
                        .HasForeignKey("ZeroToHero.CodeFirst.DAL.Employee", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroToHero.CodeFirst.DAL.Manager", b =>
                {
                    b.HasOne("ZeroToHero.CodeFirst.DAL.BasePerson", null)
                        .WithOne()
                        .HasForeignKey("ZeroToHero.CodeFirst.DAL.Manager", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
